// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMEsGSL5vI6NlVt9Maly-F9Lt9y8VZ1Us',
    appId: '1:976536236598:web:a5757a0ef7b23d6c209e97',
    messagingSenderId: '976536236598',
    projectId: 'smart-campus-ert',
    authDomain: 'smart-campus-ert.firebaseapp.com',
    storageBucket: 'smart-campus-ert.firebasestorage.app',
    measurementId: 'G-XJSZ9ZTR6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6pD9JLDstVjsd76ntgOsYNDi8v4brFkg',
    appId: '1:976536236598:android:307dfb2798400331209e97',
    messagingSenderId: '976536236598',
    projectId: 'smart-campus-ert',
    storageBucket: 'smart-campus-ert.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDgVx8e0oK3PLfaap0VpmUJkKu7qv5WCg',
    appId: '1:976536236598:ios:b48769375b2c6ba4209e97',
    messagingSenderId: '976536236598',
    projectId: 'smart-campus-ert',
    storageBucket: 'smart-campus-ert.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusErp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDgVx8e0oK3PLfaap0VpmUJkKu7qv5WCg',
    appId: '1:976536236598:ios:b48769375b2c6ba4209e97',
    messagingSenderId: '976536236598',
    projectId: 'smart-campus-ert',
    storageBucket: 'smart-campus-ert.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMEsGSL5vI6NlVt9Maly-F9Lt9y8VZ1Us',
    appId: '1:976536236598:web:5e3c3518e49d0833209e97',
    messagingSenderId: '976536236598',
    projectId: 'smart-campus-ert',
    authDomain: 'smart-campus-ert.firebaseapp.com',
    storageBucket: 'smart-campus-ert.firebasestorage.app',
    measurementId: 'G-S7KSSPTFRC',
  );
}
